[tools]
bun = { version = "latest", minimum_release_age = "0s" }
"npm:prettier" = "latest"
"npm:@openai/codex" = { version = "latest", minimum_release_age = "0s" }
"npm:eas-cli" = "latest"
"npm:agent-browser" = "latest"
"npm:@earendil-works/pi-coding-agent" = { version = "latest", bun_args = "--ignore-scripts", npm_args = "--ignore-scripts" }
"npm:opencode-ai" = "latest"
pnpm = "latest"
rust = "stable"
uv = "latest"
fnox = "latest"

[settings]
experimental = true

[settings.npm]
bun = true
